### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}

### teszt
get {{host}}/api/

# ------------- login, user -------------
### login
# @name login
POST {{host}}/api/users/login 
Accept: application/json
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "123"
}

###
@token = {{login.response.body.data.token}}

### logout user
POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}


### get users
GET  {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### get user by id
GET  {{host}}/api/users/1
Accept: application/json
Authorization: Bearer {{token}}

### post user
POST {{host}}/api/users 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "test2",
    "email": "test2@example.com",
    "password": "123",
    "role_id": 1,
    "number_of_people": 2
}

### patch user
PATCH {{host}}/api/users/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "role_id": 2
}

### delete user
DELETE {{host}}/api/users/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
# ------------- /login, user -------------


# ------------- roles -------------
### get roles
GET  {{host}}/api/roles
Accept: application/json
Authorization: Bearer {{token}}

### get role by id
GET  {{host}}/api/roles/1
Accept: application/json
Authorization: Bearer {{token}}

### post role
POST {{host}}/api/roles 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "jager"
}

### patch role
PATCH {{host}}/api/roles/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "jagercsicska"
}

### delete role
DELETE {{host}}/api/roles/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
# ------------- /roles -------------


# ------------- categories -------------
### get categories
GET  {{host}}/api/categories
Accept: application/json
Authorization: Bearer {{token}}

### get categorie by id
GET  {{host}}/api/categories/12
Accept: application/json
Authorization: Bearer {{token}}

### post categorie
POST {{host}}/api/categories 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "jager",
    "meal_id": 1
}

### patch categorie
PATCH {{host}}/api/categories/13
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "jagercsicska"
}

### delete categorie
DELETE {{host}}/api/categories/13
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
# ------------- /categories -------------


# ------------- units -------------
### get units
GET  {{host}}/api/units
Accept: application/json
Authorization: Bearer {{token}}

### get units by id
GET  {{host}}/api/units/13
Accept: application/json
Authorization: Bearer {{token}}

### post unit
POST {{host}}/api/units 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "jager",
    "meal_id": 1
}

### patch unit
PATCH {{host}}/api/units/13
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "jagercsicska"
}

### delete unit
DELETE {{host}}/api/units/13
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
# ------------- /units -------------


# ------------- ingredients -------------

# ------------- /ingredients -------------


# ------------- dishes -------------

# ------------- /dishes -------------


# ------------- components -------------

# ------------- /components -------------


# ------------- meals -------------

# ------------- /meals -------------


# ------------- daily_menus -------------

# ------------- /daily_menus -------------


# ------------- menu_items -------------

# ------------- /menu_items -------------


# ------------- dish_meals -------------

# ------------- /dish_meals -------------